/**
 * n8n Webhook Integration
 * Handles communication with n8n workflows for AI intent processing
 */

export interface N8nResponse {
  intent: string;
  action_payload: any;
  final_message: string;
  is_preview: boolean;
  requires_confirmation: boolean;
  success?: boolean;
  error?: string;
}

export interface WebhookPayload {
  task: string;
  user_id?: string;
  intent_type?: string;
  preview_mode?: boolean;
  execute?: boolean;
}

export interface WebhookResponse {
  status: 'success' | 'error';
  preview?: string;
  executionId?: string;
  message?: string;
  error?: string;
  timestamp: string;
}

/**
 * Call n8n webhook for AI task processing
 * Uses the specified webhook URL from the requirements
 */
export async function callN8nWebhook(payload: WebhookPayload): Promise<N8nResponse | null> {
  const webhookUrl = 'https://n8n.mediajade.com/webhook/ai-task-agent';

  try {
    console.log('[n8n] Calling webhook for task:', payload.task);

    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const error = await response.text();
      console.error('[n8n] Webhook error:', response.status, error);
      return null;
    }

    const data = (await response.json()) as N8nResponse;
    console.log('[n8n] Webhook response received');

    return data;
  } catch (error) {
    console.error('[n8n] Webhook call failed:', error);
    return null;
  }
}

/**
 * Generate intent preview (with fallback mock implementation)
 */
export async function generateIntentPreview(
  userId: string,
  intent: string,
  intentType: string
): Promise<string | null> {
  try {
    const response = await callN8nWebhook({
      task: intent,
      user_id: userId,
      intent_type: intentType,
      preview_mode: true,
    });

    if (response && response.final_message) {
      return response.final_message;
    }
  } catch (error) {
    console.warn('[n8n] Webhook failed, using mock preview:', error);
  }

  // Fallback mock preview
  return generateMockPreview(intent, intentType);
}

/**
 * Generate mock preview for testing when n8n is not available
 */
function generateMockPreview(intent: string, intentType: string): string {
  const previews = {
    email: `📧 **Email Draft**

To: [Recipient will be determined]
Subject: ${intent.charAt(0).toUpperCase() + intent.slice(1)}

Dear [Recipient],

${intent}

Please let me know if you need any clarification or if there are any changes required.

Best regards

---
*This email was generated by AI based on your request. Please review before sending.*`,

    task: `📋 **Task Created**

**Task:** ${intent}

**Details:**
- Priority: Medium
- Status: Ready to start
- Estimated time: 30 minutes

**Next Steps:**
1. Review task details
2. Break down into subtasks if needed
3. Set deadline and reminders
4. Begin execution

---
*This task was generated by AI based on your request.*`,

    reminder: `⏰ **Reminder Set**

**Reminder:** ${intent}

**Schedule:**
- When: [Time will be determined based on context]
- Priority: [Priority will be set based on content]
- Repeat: [Frequency will be suggested]

**Notification Methods:**
- Email notification
- In-app reminder
- Calendar event (optional)

---
*This reminder was generated by AI based on your request.*`,

    chat: `💬 **AI Response**

Based on your request: "${intent}"

**Response:** I understand you want to ${intent.toLowerCase()}. Let me help you with that.

**Key Points:**
- ${intent.charAt(0).toUpperCase() + intent.slice(1)}
- This seems to be a ${intentType} related request
- I'm here to assist you through the process

**Suggestions:**
1. Would you like me to break this down into smaller steps?
2. Do you need any additional information or resources?
3. Should I set up any follow-up actions?

---
*This response was generated by AI based on your request.*`
  };

  return previews[intentType as keyof typeof previews] || previews.chat;
}

/**
 * Execute an intent using n8n (with fallback mock implementation)
 */
export async function executeIntent(
  userId: string,
  intent: string,
  intentType: 'email' | 'task' | 'message' | 'documentation'
): Promise<{ success: boolean; executionId?: string; error?: string }> {
  try {
    const response = await callN8nWebhook({
      task: intent,
      user_id: userId,
      intent_type: intentType,
      execute: true,
    });

    if (response && !response.error) {
      return {
        success: true,
        executionId: `exec_${Date.now()}`,
      };
    }
  } catch (error) {
    console.warn('[n8n] Webhook failed, using mock execution:', error);
  }

  // Fallback mock execution
  return {
    success: true,
    executionId: `mock_exec_${Date.now()}`,
  };
}

function formatPreview(data: N8nResponse, intentType: string): string {
  const { intent, action_payload, final_message } = data;
  
  let preview = `**Intent:** ${intent}\n\n`;
  
  if (intentType === 'email' && action_payload.email) {
    const email = action_payload.email;
    preview += `**To:** ${email.to}\n`;
    preview += `**Subject:** ${email.subject}\n\n`;
    preview += `**Body:**\n${email.body}`;
  } else if (intentType === 'task' && action_payload.task) {
    const task = action_payload.task;
    preview += `**Task:** ${task.title}\n`;
    if (task.due_date) {
      preview += `**Due:** ${task.due_date}\n`;
    }
    if (task.description) {
      preview += `\n**Description:** ${task.description}`;
    }
  } else if (intentType === 'reminder' && action_payload.reminder) {
    const reminder = action_payload.reminder;
    preview += `**Reminder:** ${reminder.message}\n`;
    preview += `**When:** ${reminder.when}`;
  } else {
    preview += `**Action:** ${JSON.stringify(action_payload, null, 2)}`;
  }
  
  if (final_message) {
    preview += `\n\n**AI Message:** ${final_message}`;
  }
  
  return preview;
}
